CREATE TABLE IF NOT EXISTS `pilots`
(`pilotid` VARCHAR(255) PRIMARY KEY NOT NULL,
`firstname` VARCHAR(255) DEFAULT NULL,
`lastname` VARCHAR(255) DEFAULT NULL,
`phone` VARCHAR(255) DEFAULT NULL,
`date` DATETIME DEFAULT CURRENT_TIMESTAMP(),
`email` VARCHAR(255) DEFAULT NULL,
`distance` INT DEFAULT 100)